In [16]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [19]:
x=np.array([1,2,3,4,5])
y=np.array([1,4,9,16,25])
print(x)
print(y)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [20]:
train_x,test_x,train_y,test_y=train_test_split(x,y)
print(train_x,test_x,train_y,test_y)

[4 1 2] [3 5] [16  1  4] [ 9 25]


In [12]:
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [13]:
y_pred=model.predict(x)
print(y_pred)
print(model.score(x,y_pred))

[-1.  5. 11. 17. 23.]
1.0


In [15]:
x_new=np.arange(7).reshape(-1,1)
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
