In [2]:
import numpy as np
arr=np.array([7,8,9,10])
print(arr)
arr1=np.array([[1,2,3],[4,5,7]])
arr1

[ 7  8  9 10]


array([[1, 2, 3],
       [4, 5, 7]])

In [4]:

arr1.ndim

2

In [5]:
arr.ndim

1

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr1.dtype

dtype('int32')

In [11]:
import numpy as np
arr3=np.zeros((3,2),dtype=int)
print(arr3)


[[0 0]
 [0 0]
 [0 0]]


In [14]:

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros(2)

array([0., 0.])

In [16]:
import numpy as np
arr4=np.ones((3,2),dtype=int)
print(arr4)


[[1 1]
 [1 1]
 [1 1]]


In [22]:
import numpy as np
arr5=np.empty(3)
print(arr5)

[ 1.12944721e-311  0.00000000e+000 -4.94065646e-324]


In [21]:
np.empty(2)

array([1.69759663e-313, 2.12199579e-313])

In [24]:
import numpy as np
arr=np.arange(0,10,2)
arr

array([2, 4, 6, 8])

In [26]:
arr1=np.arange(2,10,3)
arr1

array([2, 5, 8])

In [27]:
arr1=np.arange(20,200,10,float)
arr1

array([ 20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120.,
       130., 140., 150., 160., 170., 180., 190.])

In [28]:
import numpy as np
arr=np.linspace(10,20,5)
arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [29]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
arr1=np.linspace(0,10,5)
arr1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
arr1=np.linspace(0,10,5,endpoint=True,retstep=True)
arr1

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

In [44]:
arr1=np.linspace(0,10,5,endpoint=False,retstep=True)
arr1

(array([0., 2., 4., 6., 8.]), 2.0)

In [46]:
a=np.ones(3,dtype=np.int64)
a

array([1, 1, 1], dtype=int64)

In [49]:
arr1=np.array([1,7,2,3,8,5,4,6])
np.sort(arr1)
print(arr1)

[1 7 2 3 8 5 4 6]


In [50]:
a=np.array([4,2,3])
np.argsort(a)

array([1, 2, 0], dtype=int64)

In [54]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
c=np.concatenate((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
c=np.concatenate((a,b),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b),axis=1)

c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [58]:
d=np.concatenate((a,b),axis=0)
d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [60]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
c=np.concatenate((a,b),axis=None)
c

array([1, 2, 3, 4, 5, 6])

In [63]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.ndim

2

In [64]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
a.size

9

In [66]:
a.itemsize

4

In [70]:
a=np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(a.shape)

(2, 5)


In [71]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [88]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
b=a.reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
import numpy as np
arr1=np.array([[1,7,2],[3,8,5,4]])
arr1

C:\Users\GAJALA~1\AppData\Local\Temp/ipykernel_2452/3332370302.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1=np.array([[1,7,2],[3,8,5,4]])


array([list([1, 7, 2]), list([3, 8, 5, 4])], dtype=object)

In [8]:
arr2=arr1[np.newaxis,:]
arr2.shape

(1, 2)

In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a2=a[np.newaxis]
a2.shape

(1, 3, 3)

In [15]:
a=np.array([1,2,3,4,5,6])
a[5]

6

In [16]:
a[0:4]

array([1, 2, 3, 4])

In [17]:
a[1:6]

array([2, 3, 4, 5, 6])

In [18]:
a[ : ]

array([1, 2, 3, 4, 5, 6])

In [19]:
a[2:]

array([3, 4, 5, 6])

In [20]:
a[-1:]

array([6])

In [32]:
b=np.array([[6,7,8],[9,10,11]])
b


array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
np.stack((a,b))


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [35]:
np.hstack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [36]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
np.dstack((a,b))

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [43]:
import numpy as np
arr1=np.array([1,7,2,3,8,5])
np.hsplit(arr1,2)

[array([1, 7, 2]), array([3, 8, 5])]

In [44]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
b=np.array([[6,7,8],[9,10,11]])
b


array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [47]:
a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [48]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [49]:
a/b

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [58]:
a=np.array([1,2,3,4,5])
a
a.sum()

15

In [59]:
a.min()

1

In [60]:
b=np.array([[1,2],[3,4]])
b.sum(axis=1)

array([3, 7])

In [61]:
a.max()

5

In [55]:
b.sum(axis=0)

array([4, 6])

In [63]:
a=np.array([1,2,3,4,5,6,7,1,6,3,6,7,8,5,7,9,6,1324,4,653])
b=np.unique(a)
b

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,  653, 1324])